services:
  - type: web
    name: mdlib-2-0
    runtime: php
    plan: free
    buildCommand: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && php composer-setup.php --install-dir=/usr/local/bin --filename=composer && composer install --no-dev --optimize-autoloader && php artisan config:cache && npm ci && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
      - key: LOG_CHANNEL
        value: errorlog
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
